services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - ./config:/config 
      - ./cache:/cache
      - type: bind
        ... smb? or just mounts ...
    restart: 'unless-stopped'
