# 
#  █▄░█ █▀█ █▀▄▀█
#  █░▀█ █▀▀ █░▀░█
#
#  docker compose for nginx-proxy-manager

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '40080:80'
      - '40443:443'
      - '40081:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
